name: state_testing_dashboard
version: 1.0.0
config-version: 2
profile: state_testing_dashboard
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  state_testing_dashboard:
    staging:
      +materialized: view

    marts:
      +materialized: table
