SELECT
    StudentIdentifier,
    COUNT(*) AS rows_per_student
FROM dim_students
GROUP BY StudentIdentifier
HAVING COUNT(*) > 1
ORDER BY rows_per_student DESC;

SELECT *
FROM stg_state_testing
WHERE StudentIdentifier = '8164841e9681b5f392fa918e55444bf6';

SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME() || '.snowflakecomputing.com';

SHOW USERS LIKE 'cadupee';

SHOW PARAMETERS LIKE 'AUTHENTICATION POLICY' IN ACCOUNT;

USE ROLE SECURITYADMIN;

CREATE ROLE POWERBI_READER;

GRANT USAGE ON WAREHOUSE COMPUTE_WH
TO ROLE POWERBI_READER;

GRANT USAGE ON DATABASE STATE_TESTING_DASHBOARD
TO ROLE POWERBI_READER;

GRANT USAGE ON SCHEMA STATE_TESTING_DASHBOARD.DEV
TO ROLE POWERBI_READER;

GRANT SELECT ON ALL TABLES IN SCHEMA STATE_TESTING_DASHBOARD.DEV
TO ROLE POWERBI_READER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA STATE_TESTING_DASHBOARD.DEV
TO ROLE POWERBI_READER;

GRANT SELECT ON ALL VIEWS IN SCHEMA STATE_TESTING_DASHBOARD.DEV
TO ROLE POWERBI_READER;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA STATE_TESTING_DASHBOARD.DEV
TO ROLE POWERBI_READER;

USE ROLE USERADMIN;

CREATE USER POWERBI_SERVICE
    TYPE = SERVICE
    DEFAULT_ROLE = POWERBI_READER
    DEFAULT_WAREHOUSE = COMPUTE_WH
    RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzJoD9vOalUbmbCzIhoUa0erBTxfCZ7Lj9G2qXXYI5+K5XVEetZ9cArnEAULNhifLVEDmVVe3pSWGNc6+A+N7xESLrvbgGxG0wX38ye7b9N5CdOb5UCJ2wIdL7t9NGuiA/UtsbRLU3Nqo/s7IhimVnTtz/BV46adoPOE9bY7WroSxotqPwbZEKflhBaBs8Dhhi4qyGvVbX+4LY+VukRGkpuEY5x2leiBDs+dVP//mWYxz5GTmvNK+aV1O3RaAiWMXlOemVlaP4kZWVY+NppSUbpg0Pf7dxPn2AmDATEu3azYgGbClp74R7qlh1JL1RRGYxGtSohsR10U//vKi7TXGFQIDAQAB';

USE ROLE SECURITYADMIN;

GRANT ROLE POWERBI_READER
TO USER POWERBI_SERVICE;

DESC USER POWERBI_SERVICE;

SELECT
    EVENT_TIMESTAMP,
    USER_NAME,
    FIRST_AUTHENTICATION_FACTOR,
    IS_SUCCESS,
    ERROR_CODE,
    ERROR_MESSAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE EVENT_TIMESTAMP >= DATEADD('hour', -2, CURRENT_TIMESTAMP())
ORDER BY EVENT_TIMESTAMP DESC;