with data_types as (
    select
        SCHOOLNAME::VARCHAR as schoolname,
        STUDENTIDENTIFIER::VARCHAR as StudentIdentifier,
        SUBMITDATETIME,
        SCHOOLYEAR::INTEGER as SCHOOLYEAR,
        ASSESSMENTTYPE::VARCHAR as ASSESSMENTTYPE,
        ASSESSMENTSUBTYPE::VARCHAR as ASSESSMENTSUBTYPE,
        ASSESSMENTNAME::VARCHAR as AssessmentName,
        SUBJECT::VARCHAR as SUBJECT,
        GRADELEVELWHENASSESSED::INTEGER as GRADELEVELWHENASSESSED,
        SCALESCOREACHIEVEMENTLEVEL::VARCHAR as SCALESCOREACHIEVEMENTLEVEL,
        CASE
            WHEN UPPER(TRIM(SCALESCORE)) = 'NA' THEN NULL
            ELSE SCALESCORE::NUMBER
        END AS SCALESCORE,
        MIGRANTSTATUS::VARCHAR as MIGRANTSTATUS,
        LANGUAGECODE::VARCHAR as LANGUAGECODE,
        LANGUAGEALTCODE::VARCHAR as LANGUAGEALTCODE,
        ENGLISHLANGUAGEACQUISITIONSTATUS::VARCHAR as ENGLISHLANGUAGEACQUISITIONSTATUS,
        HISPANICORLATINOETHNICITY::VARCHAR as HISPANICORLATINOETHNICITY,
        AMERICANINDIANORALASKANATIVE::VARCHAR as AMERICANINDIANORALASKANATIVE,
        ASIAN::VARCHAR as ASIAN,
        BLACKORAFRICANAMERICAN::VARCHAR as BLACKORAFRICANAMERICAN,
        WHITE::VARCHAR as WHITE,
        NATIVEHAWAIIANOROTHERPACIFICISLANDER::VARCHAR as NATIVEHAWAIIANOROTHERPACIFICISLANDER,
        TWOORMORERACES::VARCHAR as TWOORMORERACES,
        FILIPINO::VARCHAR as FILIPINO
    from {{ ref('portfolio_test_data')  }}
)

select * from data_types

